add view
whiteWolfx99/Blog_App pull request #7
Opened 2023-03-03 01:35 UTC by whiteWolfx99

# Blog app - Views

## Description
In this project you will be adding the Views associated with the Models and Controllers you've already created for your Blog App.

### Project requirements
- Implement the design from the sneak peek wireframes.
    - Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)
    
![All Users page wireframe](../images/blog_root_users.png) ![Single User page wireframe](../images/blog_user_page.png) ![All Posts by a given User page wireframe](../images/blog_user_all_posts.png) ![Single Post page wireframe](../images/blog_single_post.png)

- Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
- **Hint:** In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).

2023-03-03 03:20 UTC, FrederickMih requested changes
## Hi :raising_hand:  @whiteWolfx99 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 
- Linter checks passed :heavy_check_mark: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 03:20 UTC, FrederickMih commented on app/views/posts/index.html.erb
> +        <% post.comments.take(5).each do |comment| %>
- [ ] As requested in the requirements following the order of Milestones, you should have got a method in the Post model that does this. You were just supposed to call that method. The logic shouldn't be carried out here.

2023-03-03 03:20 UTC, FrederickMih commented on app/views/posts/show.html.erb
> +<%= @post.title + ' by ' + @user.name %>
- [ ] Please check the wireframe once more. It should be:

**Post #1 by username** and not **Post title by username**

2023-03-03 11:40 UTC, whiteWolfx99 commented on app/views/posts/show.html.erb
> +<%= @post.title + ' by ' + @user.name %>
@FrederickMih appreciates the feedback, but I disagree with you. It is simple for me to do this, but then what advantage does the title have? which, if we don't use this title, we have in post attribute.

2023-03-03 12:02 UTC, m05e5 approved these changes
**Hi @whiteWolfx99 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights

✔️ Clean and well-organized code
✔️ No Linters error
✔️ Correct Gitflow

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-03-03 12:02 UTC, merged

2023-03-04 14:48 UTC, FrederickMih commented on app/views/posts/show.html.erb
> +<%= @post.title + ' by ' + @user.name %>
@whiteWolfx99, What you are saying is correct. I can also see the title of the post hasn't been displayed on any of the pages. But to say: [**Post title** by **username**] doesn't really make sense to the user according to my thoughts. You could have rather displayed the title additionally after making sure that the requirements of the client are made since in the future you'll always adhere to client requirements.